<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
  public function findConsultLogos()
    {
        $queryString = "images/consultLogos";
	$qb = $this->getEntityManager()
		->createQuery('select i from AppBundle:Image i WHERE i.url LIKE :searchterm')
                ->setParameter('searchterm','%'.$queryString.'%')
                ->getResult();

 	return $qb;
    }

    public function findNgosLogos()
    {
        $queryString = "images/ngosLogos";
	$qb = $this->getEntityManager()
		->createQuery('select i from AppBundle:Image i WHERE i.url LIKE :searchterm')
                ->setParameter('searchterm','%'.$queryString.'%')
                ->getResult();

 	return $qb;
    }

    public function findLogos()
    {
        $queryString = "images/logos/";
	$qb = $this->getEntityManager()
		->createQuery('select i from AppBundle:Image i WHERE i.url LIKE :searchterm')
                ->setParameter('searchterm','%'.$queryString.'%')
                ->getResult();

 	return $qb;
    }
}
