<?php

// src/AppBundle/Repository/NewsRepository.php
namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{

  public function findNews()
    {
    $now = new \Datetime();
    $qb = $this->createQueryBuilder('n')
	       ->select('n')
	       ->where('(DATEDIFF( :now,  n.start_date)/30) <=3')
	       ->setParameter('now',$now)
	       ->orderBy('n.start_date')
	       ->getQuery()
	       ->getResult();

    return $qb;
    }
}
