<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SketchfabModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SketchfabModelRepository extends EntityRepository
{
  public function findAllOrderedById()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT m FROM AppBundle:SketchfabModel m ORDER BY m.id ASC'
            )
            ->getResult();
    }
}
